steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/ai-portfolio/supportpilot-ai:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/ai-portfolio/supportpilot-ai:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - supportpilot-ai
      - --image
      - asia-south1-docker.pkg.dev/$PROJECT_ID/ai-portfolio/supportpilot-ai:$COMMIT_SHA
      - --region
      - asia-south1
      - --platform
      - managed
      - --service-account
      - supportpilot-runner@phaneendra-ai-portfolio.iam.gserviceaccount.com
      - --allow-unauthenticated
      - --port
      - "8080"
      - --cpu
      - "1"
      - --memory
      - "1Gi"
      - --timeout
      - "300"
      - --concurrency
      - "20"
      - --max-instances
      - "3"
      - --min-instances
      - "0"
      - --set-env-vars
      - APP_ENV=production
      - --set-secrets
      - DATABASE_URL=SUPPORTPILOT_DATABASE_URL:latest,GEMINI_API_KEY=SUPPORTPILOT_GEMINI_API_KEY:latest,OPERATOR_USERNAME=SUPPORTPILOT_OPERATOR_USERNAME:latest,OPERATOR_PASSWORD=SUPPORTPILOT_OPERATOR_PASSWORD:latest

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/ai-portfolio/supportpilot-ai:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
