from types import SimpleNamespace
from typing import Any

from google.genai import types
from sqlalchemy import delete, select

import app.agent.orchestrator as orchestrator

from app.agent.schemas import (
    KnowledgePassage,
    KnowledgeSearchResult,
    SubscriptionResult,
)
from app.db.models import (
    AgentRun,
    Conversation,
    Message,
    ToolExecution,
)
from app.db.session import SessionLocal


class FakeModels:
    """
    Minimal replacement for client.models.

    Each call to generate_content returns the
    next predefined fake Gemini response.
    """

    def __init__(
        self,
        responses: list[Any],
    ) -> None:
        self._responses = iter(
            responses
        )

    def generate_content(
        self,
        **_kwargs: Any,
    ) -> Any:
        response = next(
            self._responses
        )

        if isinstance(
            response,
            Exception,
        ):
            raise response

        return response


class FakeGeminiClient:
    """
    Minimal replacement for google.genai.Client.
    """

    def __init__(
        self,
        responses: list[Any],
    ) -> None:
        self.models = FakeModels(
            responses
        )


def make_tool_call_response(
    tool_name: str,
    arguments: dict[str, Any],
) -> Any:
    """
    Simulate Gemini requesting a tool.
    """

    function_call = SimpleNamespace(
        name=tool_name,
        args=arguments,
    )

    model_content = types.Content(
        role="model",
        parts=[
            types.Part.from_text(
                text=(
                    f"Calling {tool_name}"
                )
            )
        ],
    )

    return SimpleNamespace(
        function_calls=[
            function_call
        ],
        candidates=[
            SimpleNamespace(
                content=model_content
            )
        ],
        text=None,
    )


def make_final_response(
    text: str,
) -> Any:
    """
    Simulate Gemini returning its final
    customer-facing answer.
    """

    return SimpleNamespace(
        function_calls=[],
        candidates=[],
        text=text,
    )


def install_fake_client(
    monkeypatch,
    responses: list[Any],
) -> None:
    """
    Replace the live Gemini client so workflow
    tests consume zero external API quota.
    """

    fake_client = FakeGeminiClient(
        responses
    )

    monkeypatch.setattr(
        orchestrator.settings,
        "gemini_api_key",
        "test-api-key",
    )

    monkeypatch.setattr(
        orchestrator.genai,
        "Client",
        lambda **_kwargs: fake_client,
    )


def cleanup_conversation(
    conversation_id: str,
) -> None:
    """
    Remove database records generated by one
    workflow test.

    This keeps the local development database
    clean after pytest completes.
    """

    with SessionLocal() as db:
        run_ids = list(
            db.scalars(
                select(
                    AgentRun.run_id
                ).where(
                    AgentRun.conversation_id
                    == conversation_id
                )
            ).all()
        )

        if run_ids:
            db.execute(
                delete(
                    ToolExecution
                ).where(
                    ToolExecution.run_id.in_(
                        run_ids
                    )
                )
            )

        db.execute(
            delete(
                Message
            ).where(
                Message.conversation_id
                == conversation_id
            )
        )

        db.execute(
            delete(
                AgentRun
            ).where(
                AgentRun.conversation_id
                == conversation_id
            )
        )

        db.execute(
            delete(
                Conversation
            ).where(
                Conversation.conversation_id
                == conversation_id
            )
        )

        db.commit()


def test_v1_prompt_contains_evidence_guardrails() -> None:
    prompt = (
        orchestrator
        .SYSTEM_PROMPT
        .lower()
    )

    assert (
        "candidate evidence"
        in prompt
    )

    assert (
        "similarity score"
        in prompt
    )

    assert (
        "missing documentation"
        in prompt
    )

    assert (
        "does not mean"
        in prompt
    )

    assert (
        "lifetime subscription"
        in prompt
    )

    assert (
        "bitcoin"
        in prompt
    )

    assert (
        orchestrator.PROMPT_VERSION
        == "v1-agent-foundation-3"
    )


def test_v1_tool_intent_mapping() -> None:
    assert (
        orchestrator._intent_from_tool(
            "get_customer"
        )
        == "customer_account"
    )

    assert (
        orchestrator._intent_from_tool(
            "get_subscription"
        )
        == "subscription"
    )

    assert (
        orchestrator._intent_from_tool(
            "get_service_status"
        )
        == "service_status"
    )

    assert (
        orchestrator._intent_from_tool(
            "search_knowledge_base"
        )
        == "knowledge"
    )

    assert (
        orchestrator._intent_from_tool(
            "unknown_tool"
        )
        == "unknown"
    )


def test_invalid_tool_arguments_are_rejected() -> None:
    result = orchestrator._execute_tool(
        db=None,
        tool_name="get_subscription",
        arguments={},
    )

    assert (
        result["status"]
        == "ERROR"
    )

    assert (
        "Invalid tool arguments"
        in result["error"]
    )


def test_general_response_without_tool_is_persisted(
    monkeypatch,
) -> None:
    install_fake_client(
        monkeypatch,
        [
            make_final_response(
                (
                    "That request is outside "
                    "SupportPilot's CloudDesk "
                    "support scope."
                )
            )
        ],
    )

    result = orchestrator.run_agent(
        message=(
            "Who will win the next "
            "cricket World Cup?"
        ),
        customer_id=None,
    )

    conversation_id = (
        result["conversation_id"]
    )

    try:
        assert (
            result["intent"]
            == "general"
        )

        assert (
            len(
                result["trace"]
            )
            == 2
        )

        assert (
            result["trace"][0]["type"]
            == "request"
        )

        assert (
            result["trace"][1]["type"]
            == "final_response"
        )

        with SessionLocal() as db:
            agent_run = db.get(
                AgentRun,
                result["run_id"],
            )

            assert (
                agent_run
                is not None
            )

            assert (
                agent_run.intent
                == "general"
            )

            assert (
                agent_run.prompt_version
                == "v1-agent-foundation-3"
            )

            executions = list(
                db.scalars(
                    select(
                        ToolExecution
                    ).where(
                        ToolExecution.run_id
                        == result["run_id"]
                    )
                ).all()
            )

            assert (
                executions
                == []
            )

            messages = list(
                db.scalars(
                    select(
                        Message
                    )
                    .where(
                        Message.conversation_id
                        == conversation_id
                    )
                    .order_by(
                        Message.created_at
                    )
                ).all()
            )

            assert [
                message.role
                for message in messages
            ] == [
                "user",
                "assistant",
            ]

    finally:
        cleanup_conversation(
            conversation_id
        )


def test_subscription_tool_workflow_and_trace(
    monkeypatch,
) -> None:
    install_fake_client(
        monkeypatch,
        [
            make_tool_call_response(
                "get_subscription",
                {
                    "customer_id":
                        "CUS-1007"
                },
            ),
            make_final_response(
                (
                    "You are currently on "
                    "the Basic plan."
                )
            ),
        ],
    )

    def fake_get_subscription(
        _db,
        payload,
    ) -> SubscriptionResult:
        assert (
            payload.customer_id
            == "CUS-1007"
        )

        return SubscriptionResult(
            status="SUCCESS",
            subscription_id="SUB-1007",
            customer_id="CUS-1007",
            plan="BASIC",
            subscription_status=(
                "ACTIVE"
            ),
            requested_plan="PRO",
            last_sync_status="FAILED",
            error=None,
        )

    monkeypatch.setattr(
        orchestrator,
        "get_subscription",
        fake_get_subscription,
    )

    result = orchestrator.run_agent(
        message=(
            "What subscription plan "
            "am I currently on?"
        ),
        customer_id="CUS-1007",
    )

    conversation_id = (
        result["conversation_id"]
    )

    try:
        assert (
            result["intent"]
            == "subscription"
        )

        assert (
            result["response"]
            == (
                "You are currently on "
                "the Basic plan."
            )
        )

        tool_events = [
            event
            for event
            in result["trace"]
            if event["type"]
            == "tool_call"
        ]

        assert (
            len(tool_events)
            == 1
        )

        tool_event = (
            tool_events[0]
        )

        assert (
            tool_event["tool"]
            == "get_subscription"
        )

        assert (
            tool_event[
                "result_status"
            ]
            == "SUCCESS"
        )

        assert (
            tool_event[
                "result"
            ]["plan"]
            == "BASIC"
        )

        assert (
            tool_event[
                "result"
            ]["requested_plan"]
            == "PRO"
        )

        with SessionLocal() as db:
            execution = db.scalar(
                select(
                    ToolExecution
                ).where(
                    ToolExecution.run_id
                    == result["run_id"]
                )
            )

            assert (
                execution
                is not None
            )

            assert (
                execution.tool_name
                == "get_subscription"
            )

            assert (
                execution.result_status
                == "SUCCESS"
            )

            agent_run = db.get(
                AgentRun,
                result["run_id"],
            )

            assert (
                agent_run
                is not None
            )

            assert (
                agent_run.intent
                == "subscription"
            )

    finally:
        cleanup_conversation(
            conversation_id
        )


def test_unsupported_knowledge_fact_uses_safe_response(
    monkeypatch,
) -> None:
    """
    Exercise the knowledge-tool workflow without
    making a real Gemini embedding request.

    The retrieved passage is semantically related
    to subscriptions but does NOT establish
    whether lifetime plans exist.
    """

    safe_response = (
        "The available CloudDesk documentation "
        "does not provide enough information "
        "to confirm whether CloudDesk offers "
        "a lifetime subscription plan."
    )

    install_fake_client(
        monkeypatch,
        [
            make_tool_call_response(
                "search_knowledge_base",
                {
                    "query": (
                        "CloudDesk lifetime "
                        "subscription plan"
                    ),
                    "top_k": 3,
                },
            ),
            make_final_response(
                safe_response
            ),
        ],
    )

    def fake_knowledge_search(
        _db,
        _payload,
    ) -> KnowledgeSearchResult:
        return KnowledgeSearchResult(
            status="SUCCESS",
            results=[
                KnowledgePassage(
                    content=(
                        "CloudDesk subscription "
                        "charges are generally "
                        "non-refundable after a "
                        "billing cycle begins."
                    ),
                    source=(
                        "refund_policy.md"
                    ),
                    score=0.7414,
                )
            ],
            retrieval_mode=(
                "semantic-pgvector-"
                "gemini-embedding-2"
            ),
            error=None,
        )

    monkeypatch.setattr(
        orchestrator,
        "search_knowledge_base",
        fake_knowledge_search,
    )

    result = orchestrator.run_agent(
        message=(
            "Does CloudDesk provide a "
            "lifetime subscription plan?"
        ),
        customer_id=None,
    )

    conversation_id = (
        result["conversation_id"]
    )

    try:
        assert (
            result["intent"]
            == "knowledge"
        )

        assert (
            result["response"]
            == safe_response
        )

        assert (
            "does not offer"
            not in result[
                "response"
            ].lower()
        )

        tool_events = [
            event
            for event
            in result["trace"]
            if event["type"]
            == "tool_call"
        ]

        assert (
            len(tool_events)
            == 1
        )

        assert (
            tool_events[0]["tool"]
            == "search_knowledge_base"
        )

        assert (
            tool_events[0][
                "result_status"
            ]
            == "SUCCESS"
        )

        assert (
            tool_events[0][
                "result"
            ]["results"][0][
                "source"
            ]
            == "refund_policy.md"
        )

        with SessionLocal() as db:
            execution = db.scalar(
                select(
                    ToolExecution
                ).where(
                    ToolExecution.run_id
                    == result["run_id"]
                )
            )

            assert (
                execution
                is not None
            )

            assert (
                execution.tool_name
                == "search_knowledge_base"
            )

            assert (
                execution.result_status
                == "SUCCESS"
            )

    finally:
        cleanup_conversation(
            conversation_id
        )