from datetime import datetime, timezone
from decimal import Decimal
from types import SimpleNamespace
from typing import Any

from google.genai import types
from sqlalchemy import delete, select

import app.agent.orchestrator as orchestrator

from app.agent.schemas import (
    CustomerResult,
    PaymentResult,
    SubscriptionResult,
)
from app.db.models import (
    ActionExecution,
    ActionProposal,
    AgentRun,
    Conversation,
    Message,
    RefundReview,
    SupportTicket,
    ToolExecution,
)
from app.db.session import SessionLocal


class FakeModels:
    """
    Minimal replacement for client.models.

    Every generate_content call returns the next
    predefined Gemini response.
    """

    def __init__(
        self,
        responses: list[Any],
    ) -> None:
        self._responses = iter(
            responses
        )

    def generate_content(
        self,
        **_kwargs: Any,
    ) -> Any:
        response = next(
            self._responses
        )

        if isinstance(
            response,
            Exception,
        ):
            raise response

        return response


class FakeGeminiClient:
    """
    Minimal fake Gemini client used so V2
    workflow tests consume no API quota.
    """

    def __init__(
        self,
        responses: list[Any],
    ) -> None:
        self.models = FakeModels(
            responses
        )


def make_tool_call_response(
    tool_name: str,
    arguments: dict[str, Any],
) -> Any:
    """
    Simulate Gemini requesting one approved tool.
    """

    function_call = SimpleNamespace(
        name=tool_name,
        args=arguments,
    )

    model_content = types.Content(
        role="model",
        parts=[
            types.Part.from_text(
                text=(
                    f"Calling {tool_name}"
                )
            )
        ],
    )

    return SimpleNamespace(
        function_calls=[
            function_call
        ],
        candidates=[
            SimpleNamespace(
                content=model_content
            )
        ],
        text=None,
    )


def make_final_response(
    text: str,
) -> Any:
    """
    Simulate Gemini completing the investigation
    and returning its customer-facing answer.
    """

    return SimpleNamespace(
        function_calls=[],
        candidates=[],
        text=text,
    )


def install_fake_client(
    monkeypatch,
    responses: list[Any],
) -> None:
    """
    Replace the live Gemini client.

    No real Gemini API request is made during
    this workflow test.
    """

    fake_client = FakeGeminiClient(
        responses
    )

    monkeypatch.setattr(
        orchestrator.settings,
        "gemini_api_key",
        "test-api-key",
    )

    monkeypatch.setattr(
        orchestrator.genai,
        "Client",
        lambda **_kwargs: fake_client,
    )


def cleanup_conversation(
    conversation_id: str,
) -> None:
    """
    Remove records generated by this test so the
    development database remains clean.
    """

    with SessionLocal() as db:
        run_ids = list(
            db.scalars(
                select(
                    AgentRun.run_id
                ).where(
                    AgentRun.conversation_id
                    == conversation_id
                )
            ).all()
        )

        if run_ids:
            proposal_ids = list(
                db.scalars(
                    select(
                        ActionProposal.proposal_id
                    ).where(
                        ActionProposal.run_id.in_(
                            run_ids
                        )
                    )
                ).all()
            )

            if proposal_ids:
                db.execute(
                    delete(
                        ActionExecution
                    ).where(
                        ActionExecution.proposal_id.in_(
                            proposal_ids
                        )
                    )
                )

                db.execute(
                    delete(
                        SupportTicket
                    ).where(
                        SupportTicket.proposal_id.in_(
                            proposal_ids
                        )
                    )
                )

                db.execute(
                    delete(
                        RefundReview
                    ).where(
                        RefundReview.proposal_id.in_(
                            proposal_ids
                        )
                    )
                )

                db.execute(
                    delete(
                        ActionProposal
                    ).where(
                        ActionProposal.proposal_id.in_(
                            proposal_ids
                        )
                    )
                )

            db.execute(
                delete(
                    ToolExecution
                ).where(
                    ToolExecution.run_id.in_(
                        run_ids
                    )
                )
            )

        db.execute(
            delete(
                Message
            ).where(
                Message.conversation_id
                == conversation_id
            )
        )

        db.execute(
            delete(
                AgentRun
            ).where(
                AgentRun.conversation_id
                == conversation_id
            )
        )

        db.execute(
            delete(
                Conversation
            ).where(
                Conversation.conversation_id
                == conversation_id
            )
        )

        db.commit()


def test_v2_subscription_upgrade_issue_uses_three_tools(
    monkeypatch,
) -> None:
    """
    Flagship V2 scenario.

    CUS-1007:
    - customer is ACTIVE
    - current plan is BASIC
    - requested plan is PRO
    - subscription sync FAILED
    - payment for PRO SUCCESS

    Gemini investigates the problem through
    three systems before returning a response.
    Support Pilot then derives and persists an
    ESCALATION_REQUIRED resolution.
    """

    final_response = (
        "Your payment for the Pro plan was successful, "
        "but your account is still on the Basic plan "
        "and the latest subscription sync failed. "
        "This issue needs additional support review."
    )

    install_fake_client(
        monkeypatch,
        [
            make_tool_call_response(
                "get_customer",
                {
                    "customer_id": "CUS-1007"
                },
            ),
            make_tool_call_response(
                "get_subscription",
                {
                    "customer_id": "CUS-1007"
                },
            ),
            make_tool_call_response(
                "get_payment_status",
                {
                    "customer_id": "CUS-1007"
                },
            ),
            make_final_response(
                final_response
            ),
        ],
    )

    def fake_get_customer(
        _db,
        payload,
    ) -> CustomerResult:
        assert (
            payload.customer_id
            == "CUS-1007"
        )

        return CustomerResult(
            status="SUCCESS",
            customer_id="CUS-1007",
            name="Ananya Reddy",
            email="ananya.reddy@example.test",
            account_status="ACTIVE",
            error=None,
        )

    def fake_get_subscription(
        _db,
        payload,
    ) -> SubscriptionResult:
        assert (
            payload.customer_id
            == "CUS-1007"
        )

        return SubscriptionResult(
            status="SUCCESS",
            subscription_id="SUB-1007",
            customer_id="CUS-1007",
            plan="BASIC",
            subscription_status="ACTIVE",
            requested_plan="PRO",
            last_sync_status="FAILED",
            error=None,
        )

    def fake_get_payment_status(
        _db,
        payload,
    ) -> PaymentResult:
        assert (
            payload.customer_id
            == "CUS-1007"
        )

        return PaymentResult(
            status="SUCCESS",
            payment_id="PAY-3007",
            customer_id="CUS-1007",
            transaction_reference="TXN-CD-3007",
            plan="PRO",
            amount=Decimal("29.00"),
            currency="USD",
            payment_status="SUCCESS",
            payment_date=datetime(
                2026,
                8,
                27,
                tzinfo=timezone.utc,
            ).isoformat(),
            error=None,
        )

    monkeypatch.setattr(
        orchestrator,
        "get_customer",
        fake_get_customer,
    )

    monkeypatch.setattr(
        orchestrator,
        "get_subscription",
        fake_get_subscription,
    )

    monkeypatch.setattr(
        orchestrator,
        "get_payment_status",
        fake_get_payment_status,
    )

    result = orchestrator.run_agent(
        message=(
            "I paid for Pro, but my account "
            "still shows Basic. What happened?"
        ),
        customer_id="CUS-1007",
    )

    conversation_id = (
        result["conversation_id"]
    )

    try:
        assert (
            result["response"]
            == (
                "I verified that the payment for the requested plan "
                "succeeded, but the requested subscription plan is "
                "still not applied because the subscription synchronization "
                "is marked as failed. I haven't changed the account, and this "
                "requires additional support review."
            )
        )

        guardrail_events = [
            event
            for event in result["trace"]
            if (
                event["type"]
                == "response_guardrail"
            )
        ]

        assert len(
            guardrail_events
        ) == 1

        resolution = result[
            "resolution"
        ]

        assert resolution is not None

        assert (
            resolution[
                "resolution_status"
            ]
            == "ESCALATION_REQUIRED"
        )

        assert (
            resolution[
                "issue_type"
            ]
            == "subscription_upgrade_failure"
        )

        action_proposal = result[
            "action_proposal"
        ]

        assert action_proposal is not None

        assert (
            action_proposal[
                "action_name"
            ]
            == "retry_subscription_sync"
        )

        assert (
            action_proposal[
                "approval_status"
            ]
            == "PENDING_APPROVAL"
        )

        tool_events = [
            event
            for event in result["trace"]
            if event["type"] == "tool_call"
        ]

        assert (
            len(tool_events)
            == 3
        )

        assert [
            event["tool"]
            for event in tool_events
        ] == [
            "get_customer",
            "get_subscription",
            "get_payment_status",
        ]

        assert all(
            event["result_status"]
            == "SUCCESS"
            for event in tool_events
        )

        resolution_events = [
            event
            for event in result["trace"]
            if event["type"] == "resolution"
        ]

        assert (
            len(resolution_events)
            == 1
        )

        assert (
            resolution_events[0][
                "resolution_status"
            ]
            == "ESCALATION_REQUIRED"
        )

        customer_result = (
            tool_events[0]["result"]
        )

        subscription_result = (
            tool_events[1]["result"]
        )

        payment_result = (
            tool_events[2]["result"]
        )

        assert (
            customer_result[
                "account_status"
            ]
            == "ACTIVE"
        )

        assert (
            subscription_result["plan"]
            == "BASIC"
        )

        assert (
            subscription_result[
                "requested_plan"
            ]
            == "PRO"
        )

        assert (
            subscription_result[
                "last_sync_status"
            ]
            == "FAILED"
        )

        assert (
            payment_result["plan"]
            == "PRO"
        )

        assert (
            payment_result[
                "payment_status"
            ]
            == "SUCCESS"
        )

        with SessionLocal() as db:
            executions = list(
                db.scalars(
                    select(
                        ToolExecution
                    ).where(
                        ToolExecution.run_id
                        == result["run_id"]
                    )
                ).all()
            )

            assert (
                len(executions)
                == 3
            )

            execution_names = {
                execution.tool_name
                for execution in executions
            }

            assert execution_names == {
                "get_customer",
                "get_subscription",
                "get_payment_status",
            }

            agent_run = db.get(
                AgentRun,
                result["run_id"],
            )

            assert (
                agent_run
                is not None
            )

            assert (
                agent_run.error
                is None
            )

            assert (
                agent_run.resolution_status
                == "ESCALATION_REQUIRED"
            )

            conversation = db.get(
                Conversation,
                conversation_id,
            )

            assert (
                conversation
                is not None
            )

            assert (
                conversation.resolution_status
                == "ESCALATION_REQUIRED"
            )

            assert (
                conversation.current_issue
                == "subscription_upgrade_failure"
            )

            messages = list(
                db.scalars(
                    select(
                        Message
                    )
                    .where(
                        Message.conversation_id
                        == conversation_id
                    )
                    .order_by(
                        Message.created_at
                    )
                ).all()
            )

            assert [
                message.role
                for message in messages
            ] == [
                "user",
                "assistant",
            ]

    finally:
        cleanup_conversation(
            conversation_id
        )


def test_v2_payment_tool_failure_cannot_become_fake_payment_fact(
    monkeypatch,
) -> None:
    """
    A required tool failure must stay UNRESOLVED even if the mocked model tries
    to turn that missing evidence into a definite customer-facing payment fact.
    """

    install_fake_client(
        monkeypatch,
        [
            make_tool_call_response(
                "get_subscription",
                {
                    "customer_id": "CUS-1007"
                },
            ),
            make_tool_call_response(
                "get_payment_status",
                {
                    "customer_id": "CUS-1007"
                },
            ),
            make_final_response(
                "Your payment definitely failed."
            ),
        ],
    )

    def fake_get_subscription(
        _db,
        payload,
    ) -> SubscriptionResult:
        return SubscriptionResult(
            status="SUCCESS",
            subscription_id="SUB-1007",
            customer_id=payload.customer_id,
            plan="BASIC",
            subscription_status="ACTIVE",
            requested_plan="PRO",
            last_sync_status="FAILED",
            error=None,
        )

    def failing_get_payment_status(
        _db,
        _payload,
    ) -> PaymentResult:
        raise TimeoutError(
            "billing service unavailable"
        )

    monkeypatch.setattr(
        orchestrator,
        "get_subscription",
        fake_get_subscription,
    )

    monkeypatch.setattr(
        orchestrator,
        "get_payment_status",
        failing_get_payment_status,
    )

    result = orchestrator.run_agent(
        message=(
            "I paid for Pro but still see Basic. "
            "Did my payment fail?"
        ),
        customer_id="CUS-1007",
    )

    conversation_id = (
        result["conversation_id"]
    )

    try:
        assert (
            result["resolution"][
                "resolution_status"
            ]
            == "UNRESOLVED"
        )

        assert (
            result["resolution"][
                "issue_type"
            ]
            == "tool_execution_failure"
        )

        assert (
            "payment definitely failed"
            not in result[
                "response"
            ].lower()
        )

        assert (
            "verified evidence"
            in result[
                "response"
            ].lower()
        )

        tool_events = [
            event
            for event in result["trace"]
            if event["type"] == "tool_call"
        ]

        assert [
            event["tool"]
            for event in tool_events
        ] == [
            "get_subscription",
            "get_payment_status",
        ]

        assert (
            tool_events[1][
                "result_status"
            ]
            == "ERROR"
        )

        guardrail_events = [
            event
            for event in result["trace"]
            if (
                event["type"]
                == "response_guardrail"
            )
        ]

        assert len(
            guardrail_events
        ) == 1

        with SessionLocal() as db:
            agent_run = db.get(
                AgentRun,
                result["run_id"],
            )

            assert agent_run is not None

            assert (
                agent_run.resolution_status
                == "UNRESOLVED"
            )

            payment_execution = db.scalar(
                select(
                    ToolExecution
                ).where(
                    ToolExecution.run_id
                    == result["run_id"],
                    ToolExecution.tool_name
                    == "get_payment_status",
                )
            )

            assert (
                payment_execution
                is not None
            )

            assert (
                payment_execution.result_status
                == "ERROR"
            )

    finally:
        cleanup_conversation(
            conversation_id
        )
